---
# tasks file for install_tomcat
- name: Insatlling_tomcat
  #shell: wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.34/bin/apache-tomcat-10.1.34.tar.gz
  shell: tar -xvf apache-tomcat-10.1.34.tar.gz
- name: start_tomcat
  shell: sh /root/apache-tomcat-10.1.34/bin/startup.sh
  register: start_log
- debug:
    var: start_log.stdout_line
